# Generated by Django 4.2 on 2023-04-24 08:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0002_auctionlists"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctionlists",
            name="category",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
