# Generated by Django 4.2 on 2023-04-24 08:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0003_alter_auctionlists_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionlists",
            name="create_time",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="auctionlists",
            name="start_price",
            field=models.FloatField(default=0),
        ),
    ]
