# Generated by Django 4.2 on 2023-04-24 08:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0004_auctionlists_create_time_auctionlists_start_price"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AuctionLists",
            new_name="AuctionList",
        ),
    ]
