# Generated by Django 4.2 on 2023-04-24 08:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0005_rename_auctionlists_auctionlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctionlist",
            name="create_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
