# Generated by Django 4.2 on 2023-04-24 09:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0007_alter_auctionlist_user_bid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="auctionlist",
            old_name="user",
            new_name="publisher",
        ),
    ]
