# Generated by Django 4.2 on 2023-04-24 09:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0009_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="content_user",
            new_name="comment_user",
        ),
    ]
