# Generated by Django 4.2 on 2023-04-24 09:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0010_rename_content_user_comment_comment_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="item",
            new_name="comment_item",
        ),
    ]
