# Generated by Django 4.2 on 2023-04-26 07:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0011_rename_item_comment_comment_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionlist",
            name="description",
            field=models.TextField(default=200, max_length=200),
            preserve_default=False,
        ),
    ]
